# Site settings
title: Yonder
email: info@yonder.fi
description: > # this means to ignore newlines until "baseurl:"
  Yonder is a try-out service for high-quality outdoors gear, operating in Helsinki, Finland.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yonder.fi" # the base hostname & protocol for your site
twitter_username: mikipernu
github_username:  mikipernu

# Build settings
markdown: kramdown
highlighter: pygments
