# Site settings
title: Arctos
email: hello@arctos.io
description: > # this means to ignore newlines until "baseurl:"
  Get close to nature, wherever you are.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arctosadventures.github.io" # the base hostname & protocol for your site
twitter_username: mikipernu
github_username:  mikipernu

# Build settings
markdown: kramdown
highlighter: rouge
